# Generated by Django 6.0.2 on 2026-02-22 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.BigIntegerField()),
                ('song_name', models.CharField(max_length=255)),
                ('song_artist', models.CharField(max_length=255)),
                ('song_album', models.CharField(max_length=255)),
                ('song_album_art', models.CharField(max_length=255)),
                ('song_preview_url', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
