# Generated by Django 6.0.2 on 2026-03-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='comment',
        ),
        migrations.AddField(
            model_name='entry',
            name='comments',
            field=models.JSONField(default=list),
        ),
    ]
