# Generated by Django 6.0.2 on 2026-03-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='song_genre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
